### ISSUE TITLE
why does the url points differently

### ISSUE THREAD

**Issue by yuvanesh10** [lula/ngx-soap#11]
I have already created both client and server file in node js and it works super fine.
But I would like to create a client in angular 4. I have solved most of the errors concering to it. But now I am stuck to this body error and the URL is pointing to the host. Please can you have a look
There are no help available from stackoverflow or other   ##forum.

  app.component.ts
  
     ngOnInit() {
     this.http.get('../assets/check_username.wsdl').subscribe(response => {
     if (response && response.text()) {
     this.soap.createClient(response.text()).then((client: Client) => {
      this.client = client;
         });
         }
        });
      }

      client_wsdl() {

     let operationBody  = {

     userName: "TEST_USER"

     };

     this.client.operation('checkUserName', operationBody)
      .then(operation => {
        if(operation.error) {
          console.log('Operation error', operation.error);
          return;
        }

        let url = operation.url.replace("http://192.168.74.266",""); (// I have saved my serverfile in this location
       
     this.http.post(url, operation.xml, { headers: operation.headers }).subscribe(

          response => {
            this.xmlResponse = response.text();
            this.jsonResponse = this.client.parseResponseBody(response.text());

          try {
              this.message = this.jsonResponse.Body.CheckUserNameResponse;
            } catch (error) { }
            this.loading = false;
          },
          err => {
            console.log("Error calling in this part", err);

           this.loading = false;
          }
        );

![error2](https://user-images.githubusercontent.com/31204042/36419417-1537caca-1632-11e8-8cae-78ae9707d25f.PNG)
 
@lula @sonicos

**Comment by lula** [comment]
1. Are your sure this works?
`this.http.get('../assets/check_username.wsdl').subscribe(response => ...`

I believe it should be:
`this.http.get('/assets/check_username.wsdl').subscribe(response => ...`

2. Why replacing host with nothing?

`let url = operation.url.replace("http://192.168.74.266",""); `

Host replacement should be done only in case your have cors problems, and in this case you have to replace the url with the proxied one and start ionic with the proxy, as mentioned in the readme. 

3. What is this server you're calling? Is it working? Can you call the web service with a tool like Soap UI or similar? The error in the screenshot indicate you can do no post to that URL. Something in the server sounds not correct.

**Comment by yuvanesh10** [comment]
1. I have changed the assests to like you have mentioned ..,the error is the exact same
2.I saved my server file in that location(192.168.74.266). You mean proxy in the sense of replacing the url with something like(""www.examples.com")

The server file what I am using has been tested with client in Node.js. It works fine there. If you dont mind can you have a look at it.

    `var soap = require('strong-soap').soap;
     var http = require('http');

    var myService = {
    CheckUserName_Service: {
        CheckUserName_Port: {
            checkUserName: function(args, soapCallback) {

                console.log('checkUserName: Entering function..');
                res.header("Access-Control-Allow-Origin", "*");
                res.header("Access-Control-Allow-Headers", "X-Requested-With");

                db.query(aqlQuery`
                LET startVertex = (FOR doc IN spec
                FILTER doc.serial_no == '"123456abcde"'
                LIMIT 2
                RETURN doc
                )[0]

                FOR v IN 1 ANY startVertex belongs_to
                RETURN v.ip`,
                {
                bindVar1: 'value',
                bindVar2: 'value',
                }
                ).then(function(response) {
                    console.log(`Retrieved documents.`, response._result);
                    soapCallback(JSON.stringify(response._result));
                })
                .catch(function(error) {
                    console.error('Error getting document', error);
                    soapCallback('Error getting document' + error.message);
                });
            }
        }
    }
     };
     var xml = require('fs').readFileSync('check_username.wsdl', 'utf8');

    var server = http.createServer(function(request,response) {
    response.end("404: Not Found: " + request.url);
     });

    var port = 8080;
    server.listen(port);

    var soapServer = soap.listen(server, '/test', myService, xml);
    soapServer.log = function(type, data) {
     console.log('Type: ' + type + ' data: ' + data);
      };
 
    console.log('SOAP service listening on port ' + port);
     `

**Comment by lula** [comment]
Well I never used strong-loop so I can't be of much help here. The error states you cannot call POST method (404 Not found), so it seems the endpoint you are calling does not exist.

> You mean proxy in the sense of replacing the url with something like(""www.examples.com")

You have to replace it with what you have configured in your proxy.conf.json. However, you have to do that only in case you have cors problems. In your case you have control of your server and you can configure (as you did) the allowed origin.

**Comment by yuvanesh10** [comment]
@lula is there no way that you can be able to help ?
Is there any other working hlep ? I have been working on this for a week now

**Comment by lula** [comment]
I'm sorry but I have no knowledge of strong-soap. Try to call you ws with SoapUI rather than creating a node client with the same strong-soap lib. Check was it the content of the wsdl after  `this.http.get('../assets/check_username.wsdl').subscribe(...`, see what is the URL of the operation and use the operation in the subsequent call.

If you could setup a repository with the server already working I might clone it and have a look.

**Comment by yuvanesh10** [comment]
@lula That would be a big help..Thank you. Give me a moment, I will upload it in github

**Comment by yuvanesh10** [comment]
@lula I have created a public gist and I have uploaded all the server side files. Please have  a look
https://gist.github.com/yuvanesh10/2a8c9cf6af659d95dd3cc8ccebfa52c4

**Comment by lula** [comment]
Just quickly checked. I cannot even load the wsdl you provided with a test app.

**Comment by yuvanesh10** [comment]
that is the working file actually..,I am able to receive the query result from the db.

**Comment by lula** [comment]
@yuvanesh10 is this a joke ahah? Or are you just trying to have me build the test case for you? 

The wsdl in the gist is broken:

<img width="910" alt="screen shot 2018-02-20 at 21 23 09" src="https://user-images.githubusercontent.com/614544/36447301-48424470-1684-11e8-8a36-d30ea3c46864.png">

And BTW, operation url is not even pointing to your soap service.

You have the 404 error because you always respond with the 404:

<img width="570" alt="screen shot 2018-02-20 at 22 41 03" src="https://user-images.githubusercontent.com/614544/36450734-2b646a26-168f-11e8-88df-2121319b566a.png">

You use a `res` object inside the soap web service without even having it anywhere in the code, so even after solving all other errors the web service throw a 500:

<img width="639" alt="screen shot 2018-02-20 at 22 41 44" src="https://user-images.githubusercontent.com/614544/36450765-4045e9ba-168f-11e8-8127-fb2071365e9b.png">

After solving all _those things up there_, and having set cors correctly on the server, ngx-soap should work as expected, as **no problem of this issue was ever related to it**.

Please remember this is an issue repository, not a teaching community. Next time you open an issue, be sure it's a real issue and not some general help about _anything_.

**Comment by yuvanesh10** [comment]
@lula Oh no..,don't think of that way..,seriously the code what I have posted over there was real working code. I was able to get the query result from the db. Since I am new to soap-wsdl protocol, I am not getting exact thing. And I have been trying to get help from other forums as well.Sorry to bother you.

**Comment by lula** [comment]
@yuvanesh10 I'm sorry I've been harsh. Hope at least you can achieve what you want to do. Cheers!

**Comment by yuvanesh10** [comment]
@lula I get it..,because the problem is so vague and I have been pestering !! sorry for that

**Comment by yuvanesh10** [comment]
@lula I just have one doubt..,why does the url keep pointing to different one. But it is accessing the serverfile.js in (192.168.72.221) ..,but I have stored the file in (192.168.72.236)
