### ISSUE TITLE
How can I check the soap message sent to server ?

### ISSUE THREAD

**Issue by yuvanesh10** [lula/ngx-soap#12]
I am using ngx-soap library. My function works but I would like to see SOAP request sent from client or in other words I would like to see the SOAP message sent from the client . I hope my question is understandable  ?

**Comment by lula** [comment]
Hello @yuvanesh10! If I understood correctly:

```
client.operation('Add', operationBody).then(operation => {
    ....
    this.http.post(url, operation.xml, { headers: operation.headers })...
```

`operation.xml` contains the SOAP payload.

**Comment by yuvanesh10** [comment]
oh yes..,i got that !!! 
console.log(operation);

got my the soap msg.!!!
