### ISSUE TITLE
new version error

### ISSUE THREAD

**Issue by yuvanesh10** [lula/ngx-soap#19]
I was using old version of ngx-soap..,everything was running fine.!! I just updated my angular project with "npm update"..,the ngx-soap module got updated too..now it is ngx-soap@0.2.2-beta6. now I have so many errors..!!
How can I install my old version..?? any help regarding this ??

**Comment by lula** [comment]
Just install the version you had before (npm install ngx-soap@<required version>) or follow the code changes as per readme.
