### ISSUE TITLE
http://localhost:4200/calculator/calculator.asmx 404 (Not Found)

### ISSUE THREAD

**Issue by gennadii-LineUp** [lula/ngx-soap#2]
I test the Example. I did 'ng serve', then opened an app at localhost.
The button 'sum' at the app makes this error:
- POST http://localhost:4200/calculator/calculator.asmx 404 (Not Found)

Any suggestions..?

**Comment by lula** [comment]
Try serving with a proxy with command `npm run serve:proxy`. That should avoid CORS problem.

**Comment by gennadii-LineUp** [comment]
Thank you! it works!
