### ISSUE TITLE
Can't build your project

### ISSUE THREAD

**Issue by samunisys** [lula/ngx-soap#20]
Hi - I installed ngx-soap into my project. I imported it into my app.module.ts. I am using your example code from app.component.ts but when I add this line: import { SOAPService, Client } from 'ngx-soap';

to my component i get the error "SOAPService is not an exported module" in VSCode. 
So...I tried cloning your project to start reverse engineering what I need to fix but can't even build your app. Can you please help me and tell me what I am doing wrong? thanks

~/Projects/ngx-soap (master)
$ npm install

> weak@1.0.1 install C:\Users\domvilsn\Projects\ngx-soap\node_modules\weak
> node-gyp rebuild

C:\Users\domvilsn\Projects\ngx-soap\node_modules\weak>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\domvilsn\Projects\ngx-soap\node_modules\weak
gyp ERR! node -v v8.11.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: weak@1.0.1 (node_modules\weak):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: weak@1.0.1 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

added 155 packages in 19.423s

**Comment by lula** [comment]
Hello @samunisys, that should've nothing to do with ngx-soap. Your missing Python (at least) as far as I can see. See node-gyp installation requirements on Windows [here](https://github.com/nodejs/node-gyp#on-windows).
