### ISSUE TITLE
Git tags for relevant commits

### ISSUE THREAD

**Issue by Rishi321** [lula/ngx-soap#21]
Hi, I just started using this library and it's pretty awesome. It makes interacting with SOAP Services really easy and intuitive.  
Since this library is under constant development it is introducing breaking changes every few weeks (or days?) which is confusing from a documentation perspective.

For example:
I installed ngx-soap via npm, and got 0.5.0, I failed to realize the `master` branch is in fact on 0.2.2 (or somewhere around) and the example app on that is not valid anymore.
I spent ~3 hours scratching my head as to why things weren't working until I started going through the code of the library myself.

Proposed fix:
Create git tags on commits pertaining to what version is on npm
Eg. Create a tag `0.5.0-beta.4` on the current commit of `angular-cli-lib`
This way people can easily compare the versions they have and know which documentation to look up.

This is also important from the perspective of rapidly changing code, the tags allow anybody to look at the code from the perspective of what version they have.
If tomorrow a new breaking change comes up, and the example app changes, I personally will no longer be able to view the example code of the version I have installed unless I know the exact commit uuid of the version (nigh impossible).

**Comment by llulani** [comment]
Hello @Rishi321 thanks for your input, you are absolutely right. I'm sorry currently there is this confusing situation and you had to waste your time trying to understand what's going on with the project. I know it is messy and quickly evolving with breaking changes, changelog is not updated... 😞. I should have done better, I agree with you. 
I will merge the branch, update readme and changelog, etc as soon as I can. Also, I'll try not to forget adding tags as well, as you correctly propose.

**Comment by lula** [comment]
I've created tags for older version (from master before merge) and latest from npm. 

Cheers!
