### ISSUE TITLE
Basic auth headers

### ISSUE THREAD

**Issue by maikelfb** [lula/ngx-soap#22]
Hello!
I'm not familiar with node-soap nor SOAP at all. 

How should I set authorization headers in `.createClient()`. I'm trying to do basic authorization.

Thanks for your effort in this lib.

**Comment by lula** [comment]
Hello @maikelfb! You can do something like this: 

```
ngOnInit() {
   this.soap.createClient('your.wsdl')
      .then(client => {
        client.addHttpHeader('Authorization', 'Basic ' + btoa(this.user + ' ' + this.password));
        this.client = client;
      })
      .catch(err => console.log('Client creation error', err));
}
```

I'm closing the issue, but feel free to reopen it if this is not working for you.

Cheers!
