### ISSUE TITLE
How to initialize CreateClient at one place on service

### ISSUE THREAD

**Issue by passionateprogram** [lula/ngx-soap#25]
I am trying to initialize CreateClient at constructor of dataservice
Then trying to access client , it says undefined.

Please find the code snippet below.
export class DataService
{
soapClient: Client;
constructor (private soapService: NgxSoapService)
{
this.soapService.createClient(<Wsdl URL>)
    .then(x=> {
      console.log(x);
      this.soapClient = x;
      console.log('Initialised Soap Client');
    })
    .catch(err => console.log(err));
}

getData():void
{
this.soapClient.call('GetData', {}).subscribe(res => console.log(res));
}
}

Please check and help me to make one client ans use for all methods

**Comment by lula** [comment]
I don't see any wsdl passed to createClient method. No client can be created without a wsdl. Did you just avoid to include in the snippet above or you correctly passed it in your real code and yet you have the error?

**Comment by lula** [comment]
Hello @passionateprogram 

> Please let me know, whether this is possible to create soap client in constructor and then use the soap client object to call wcf methods.

Yes, this is possible. See example app in repo, where the client is created in the constructor and later used in a specific method: 

```
export class AppComponent {
    client: Client;
    intA = 2;
    intB = 3;
    
    constructor(private soap: NgxSoapService) {
        this.soap.createClient('assets/calculator.wsdl').subscribe(client => this.client = client);
    }
    
    sum() {
        const body = {
          intA: this.intA,
          intB: this.intB
        };
        (<any>this.client).Add(body).subscribe((res: ISoapMethodResponse) => this.message = res.result.AddResult);
    }
}
```

> Here I want to return the result (res.result.GetUserDetailResult) instead of assign. What could be return type and also where & how can return the result (res.result.GetUserDetailResult)

`res.result` is basically the parsed JSON of the response as defined in the WSDL. In the example app the output of the sum operation (AddResponse in WSDL) is returned in AddResult element:

```
<s:element name="AddResponse">
    <s:complexType>
        <s:sequence>
            <s:element minOccurs="1" maxOccurs="1" name="AddResult" type="s:int" />
        </s:sequence>
    </s:complexType>
</s:element>
```

So you should check in your WSDL the response type of GetUserDetail method to know the structured. In your example, I would expect the the response type has a GetUserDetailResult element which holds the user detail.

Not sure if I actually answered to your question, please let me know.
