### ISSUE TITLE
Can change callback operation to promise?

### ISSUE THREAD

**Issue by Hanzofm** [lula/ngx-soap#3]
Hi,

Is possible to change the callback of the soap operation to promise way?

Thanks

**Comment by lula** [comment]
Hello @Hanzofm! A whole refactoring of the wsdl lib is something I had already planned, sooner or later. Got to be sooner I guess :). Don't expect a very quick response though as it might be quite a complicated work, I'm afraid. I'll start looking into this as soon as I can. Thanks!

**Comment by Hanzofm** [comment]
Thanks for your work/time it is very appreciated 😉

**Comment by lula** [comment]
Hello @Hanzofm! It turned out the enhancement was easier then expected. Install 0.2.2-beta3 to have Promises on operations (breaking change):

```
client.operation('Add', body).then((operation: Operation) => ... )
// or
(client as any).Add(body).then((operation: Operation) => ... )
```

Hope that is what you needed. Feel free to reopen the issue if you encounter any problems.

**Comment by adampenn** [comment]
@lula why did you switch to promises? It seems like angular uses observables as a default
