### ISSUE TITLE
How can I access a specific SOAP service?

### ISSUE THREAD

**Issue by kgyl** [lula/ngx-soap#30]
I can't find the solution. The WSDL file is:
http://ec.europa.eu/taxation_customs/vies/checkVatService.wsdl

`...
import { NgxSoapService, Client, ISoapMethodResponse } from 'ngx-soap';
...
export class PartnerFormComponent implements OnInit {
  client: Client;

  constructor(private soapService: NgxSoapService) {
    this.soapService.createClient('assets/checkVatService.wsdl')
      .then(client => {
        this.client = client;
      })
      .catch(err => console.error(err));
  }
`

I've been trying to check specific EU VAT number, but can't find the solution.

http://ec.europa.eu/taxation_customs/vies/faq.html?locale=en#item_18

I really need this to work...

**Comment by lula** [comment]
Hello @kgyl what is exactly your issue? Client is created correctly, as far as I can see.

**Comment by lula** [comment]
import { Component, OnInit } from '@angular/core';
import { NgxSoapService, Client } from 'ngx-soap';
import { map } from 'rxjs/operators';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {
  client: Client;

  constructor(private soap: NgxSoapService) {
    soap.createClient('assets/check-vat-service.wsdl')
      .then(client => {
        this.client = client;
        this.checkVat();
      })
      .catch(err => console.log(err));
  }

  ngOnInit() {
  }

  checkVat() {
    this.client.call('checkVat', {
      countryCode: 'IT',
      vatNumber: 'IT123456789'
    }).pipe(
      map(response => response.result)
    ).subscribe(result => {
      console.log('VAT is valid ', result.valid);
    });
  }
}
