### ISSUE TITLE
How do I add a request header? 

### ISSUE THREAD

**Issue by lceCandy** [lula/ngx-soap#31]
Here's my request:
```
<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Header>
    <CheckHeader xmlns="http://tempuri.org/">
      <Key>XXXXXXXXXXXX</Key>
    </CheckHeader>
  </soap:Header>
  <soap:Body>
    <GetPersons xmlns="http://tempuri.org/">
      <queryParams>
        <DictionaryEntry>
          <Key />
          <Value />
        </DictionaryEntry>
      </queryParams>
      <page>1</page>
      <resultsPerpage>20</resultsPerpage>
    </GetPersons>
  </soap:Body>
</soap:Envelope>
```
I am a novice and cannot fully understand your help document. Looking forward to your reply : )
Would it be better if you could tell me how to complete this request :P

**Comment by lula** [comment]
Hello @lceCandy assuming you created the client given the WSDL of that ws, I guess the request would become something like:

```
client.call('GetPersons', {
  queryParams: {
    DictionaryEntry: {
      Key: 'aaaaa',
      Value: 'bbbb' 
    }
  },
  page: 1,
  resultsPerPage: 20
}).subscribe(res => {
  const jsonResult = res.result;
  ...
});
```

Cheers

Luca

**Comment by akaco** [comment]
Hello @lula  thanks for your help and make this beautiful ngx-soap for Angular I just need some help 
My [API](https://www.secureapi.com.au/reseller/docs/api.php#Introduction) need Authentication in Header before any request I just try to make this But I getting Null result : 

This is my original request: 
`<env:Envelope xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:ns1="insert API namespace here">
    <env:Header>
        <ns1:Authenticate>
            <AuthenticateRequest>
                <ResellerID>R24757</ResellerID>
                <APIKey>8f0c5ff2ea3f58c40e2d7869868a2dfc</APIKey>
            </AuthenticateRequest>
        </ns1:Authenticate>
    </env:Header>
    <env:Body>
        <ns1:DomainCheck>
            <DomainCheckRequest>
                <DomainNames>
                    <item>XYZKKKKKK.com</item>
                </DomainNames>
            </DomainCheckRequest>
        </ns1:DomainCheck>
    </env:Body>
</env:Envelope>`

And this is my request which is I made it like this :

`client.call('DomainCheck', {
  queryParams: {
    DomainCheckRequest: {
       DomainNames: {
          item: 'XYZKKKKKK.com'
    }
    }
  },
  page: 1,
  resultsPerPage: 20
}).subscribe(res => {
  const jsonResult = res.result;
  ...
});`

Can you please help me to fix this and show me how can I add Authenticate in header 

Thanks

**Comment by lula** [comment]
hello @akaco please try with the following:

```
this.soap.createClient('assets/calculator.wsdl')
      .then(client => {
        client.addSoapHeader({
          'ns1:Authenticate': {
            AuthenticateRequest: {
              ResellerID: '123',
              APIKey: '123123123122112312'
            }
          }
        });
        this.client = client;
      })
      .catch(err => console.log('Error', err));
```

**Comment by akaco** [comment]
Thanks @lula ,
I just did like this but getting error `"statusText: "Unknown Error","`


```

this.soap.createClient('http://soap-test.secureapi.com.au/wsdl/API-2.0.wsdl')
      .then(client => {
        client.addSoapHeader({
          'ns1:Authenticate': {
            AuthenticateRequest: {
              ResellerID: 'R24757',
              APIKey: '8f0c5ff2ea3f58c40e2d7869868a2dfc'
            }
          }
        });
        this.client = client;
        console.log(this.client);
        this.client.call('DomainCheck', {
          DomainCheckRequest: {
            DomainNames: { item: 'cvgfdhklpounm12345.com' }
          }
        }).subscribe(res => {
          const jsonResult = res.result;
          console.log(jsonResult);
        });
      })
      .catch(err => console.log('Error', err));

```
can you please help me about that really I'm stock here and I can't figure out where is the problem 
this is the API  link https://www.secureapi.com.au/reseller/docs/api.php#Introduction

Thank you so much for your assistance. You really came through, proving what it means to be a "team player." The extra effort you put in was really appreciated.

**Comment by lula** [comment]
Hi @akaco, testing from localhost with your code above is not working, because of CORS.

To have a working test from my angular dev env I did: 

1. added a proxy (proxy.config.js):

```
{
    "/secureapi": {
      "target": "https://soap-test.secureapi.com.au",
      "secure": false,
      "changeOrigin": "true",
      "pathRewrite": {"^/secureapi": ""}
    }
  }
```
2. downloaded wsdl from http://soap-test.secureapi.com.au/wsdl/API-2.0.wsdl and updated service address accordingly: 

```
<service name="API-2.0Service">
    <port name="API-2.0Port" binding="tns:API-2.0Binding">
      <!-- <soap:address location="https://soap-test.secureapi.com.au/server.php?v=2.0"/> -->
      <soap:address location="/secureapi/server.php?v=2.0"/>
    </port>
  </service>
```

WSDL had been saved in assets dir.

3. used the updated wsdl from assets

```
this.soap.createClient('assets/secureapi.wsdl')
...
```

4. started the dev env with proxy `ng serve --proxy.config=proxy.config.js`

It seems to work this way:

<img width="1277" alt="Screenshot 2019-05-02 at 15 41 10" src="https://user-images.githubusercontent.com/614544/57079820-76f1ff80-6cf1-11e9-98d4-acaf28d355a5.png">

**Comment by evandrolamaral** [comment]
Hi,

Need some help, here my request, I need send a TOKEN to validate:

<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:eas="Easycargo16_U2">
   <soapenv:Header/>
   <soapenv:Body>
      <eas:WsGetEstados.Execute>
         <eas:Token>XXXXXXXXXXXXXXXXX</eas:Token>
      </eas:WsGetEstados.Execute>
   </soapenv:Body>
</soapenv:Envelope>


In my code:

this.soap.createClient('http://rglogistica.ddns.net:8050/easycargo15/aWsGetEstados.aspx?wsdl')
    .then(client => {
      client.addBodyAttribute({
        'eas:WsGetCidade.Execute': {
          'eas:Token': 'XXXXXXXXXXXXX'
        }
      });
     console.log('Client', client);
      this.client = client;
    })
    .catch(err => console.log('Error', err));

But I'm receive XML with no values...

<?xml version = "1.0" encoding = "utf-8"?>
<definitions name="WsGetEstados" targetNamespace="Easycargo16_U2" xmlns:wsdlns="Easycargo16_U2" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="Easycargo16_U2">
	<types>
		<schema targetNamespace="Easycargo16_U2" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" elementFormDefault="qualified">
			<complexType name="SdtWsRetorno">
				<sequence>
					<element name="CodErro" type="xsd:short">
					</element>
					<element name="MsgErro" type="xsd:string">
					</element>
					<element name="Retorno" type="xsd:string">
					</element>
				</sequence>
			</complexType>
			<element name="WsGetEstados.Execute">
				<complexType>
					<sequence>
						<element minOccurs="1" maxOccurs="1" name="Token" type="xsd:string" />
					</sequence>
				</complexType>
			</element>
			<element name="WsGetEstados.ExecuteResponse">
				<complexType>
					<sequence>
						<element minOccurs="1" maxOccurs="1" name="Sdtwsretorno" type="tns:SdtWsRetorno" />
					</sequence>
				</complexType>
			</element>
		</schema>
	</types>
	<message name="WsGetEstados.ExecuteSoapIn">
		<part name="parameters" element="tns:WsGetEstados.Execute" />
	</message>
	<message name="WsGetEstados.ExecuteSoapOut">
		<part name="parameters" element="tns:WsGetEstados.ExecuteResponse" />
	</message>
	<portType name="WsGetEstadosSoapPort">
		<operation name="Execute">
			<input message="wsdlns:WsGetEstados.ExecuteSoapIn" />
			<output message="wsdlns:WsGetEstados.ExecuteSoapOut" />
		</operation>
	</portType>
	<binding name="WsGetEstadosSoapBinding" type="wsdlns:WsGetEstadosSoapPort">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" />
		<operation name="Execute">
			<soap:operation soapAction="Easycargo16_U2action/AWSGETESTADOS.Execute" />
			<input>
				<soap:body use="literal" />
			</input>
			<output>
				<soap:body use="literal" />
			</output>
		</operation>
	</binding>
	<service name="WsGetEstados">
		<port name="WsGetEstadosSoapPort" binding="wsdlns:WsGetEstadosSoapBinding">
			<soap:address location="http://rglogistica.ddns.net:8050/easycargo15/awsgetestados.aspx" />
		</port>
	</service>
</definitions>

In SoapUI software, testing this webservice, I get:

<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
   <SOAP-ENV:Body>
      <WsGetEstados.ExecuteResponse xmlns="Easycargo16_U2">
         <Sdtwsretorno>
            <CodErro>0</CodErro>
            <MsgErro>Pesquisa realizada com sucesso!</MsgErro>
            <Retorno>[{"EstadoSigla":"AC","EstadoNome":"ACRE"},{"EstadoSigla":"AL","EstadoNome":"ALAGOAS"},{"EstadoSigla":"AM","EstadoNome":"AMAZONAS"},{"EstadoSigla":"AP","EstadoNome":"AMAPÁ"},{"EstadoSigla":"BA","EstadoNome":"BAHIA"},{"EstadoSigla":"CE","EstadoNome":"CEARÁ"},{"EstadoSigla":"DF","EstadoNome":"DISTRITO FEDERAL"},{"EstadoSigla":"ES","EstadoNome":"ESPÍRITO SANTO"},{"EstadoSigla":"EX","EstadoNome":"EXTERIOR"},{"EstadoSigla":"GO","EstadoNome":"GOIAS"},{"EstadoSigla":"MA","EstadoNome":"MARANHÃO"},{"EstadoSigla":"MG","EstadoNome":"MINAS GERAIS"},{"EstadoSigla":"MS","EstadoNome":"MATO GROSSO DO SUL"},{"EstadoSigla":"MT","EstadoNome":"MATO GROSSO"},{"EstadoSigla":"PA","EstadoNome":"PARÁ"},{"EstadoSigla":"PB","EstadoNome":"PARAÍBA"},{"EstadoSigla":"PE","EstadoNome":"PERNAMBUCO"},{"EstadoSigla":"PI","EstadoNome":"PIAUI"},{"EstadoSigla":"PR","EstadoNome":"PARANA"},{"EstadoSigla":"RJ","EstadoNome":"RIO DE JANEIRO"},{"EstadoSigla":"RN","EstadoNome":"RIO GRANDE DO NORTE"},{"EstadoSigla":"RO","EstadoNome":"RONDÔNIA"},{"EstadoSigla":"RR","EstadoNome":"RORAIMA"},{"EstadoSigla":"RS","EstadoNome":"RIO GRANDE DO SUL"},{"EstadoSigla":"SC","EstadoNome":"SANTA CATARINA"},{"EstadoSigla":"SE","EstadoNome":"SERGIPE"},{"EstadoSigla":"SP","EstadoNome":"SÃO PAULO"},{"EstadoSigla":"TO","EstadoNome":"TOCANTINS"}]</Retorno>
         </Sdtwsretorno>
      </WsGetEstados.ExecuteResponse>
   </SOAP-ENV:Body>
</SOAP-ENV:Envelope>


Please help me...
