### ISSUE TITLE
How to by pass TS2300: Duplicate identifier

### ISSUE THREAD

**Issue by cmaitrepierre** [lula/ngx-soap#32]
Hello i have a wsdl having keys with maxOccurs<xs:sequence><xs:choice minOccurs="0" maxOccurs="unbounded">. I cant write my json body (for exemple { name:'john',name='paul'} beacuse the angular 6 doesn't allow it yet. Is there a workaround to write such json body ? Best Regards Cgristophe Maitrepierre

**Comment by lula** [comment]
Hello @cmaitrepierre sorry for delay! It's not clear to me what you're trying to do. Sequences should be translated as arrays of objects.

**Comment by cmaitrepierre** [comment]
Hello @lula i have followed your advise and use an array of objects [{name:'john'},{name:'paul'}] and it is working fine. This allows to continue my project related to Radio Policy Management with angular and Gemalto AOTA (Advanced Over The Air) Platform. Best Regards, Christophe

**Comment by lula** [comment]
Hello @cmaitrepierre! Glad to hear your issue is solved!! 🎉
