### ISSUE TITLE
Access-Control-Allow-Origin'

### ISSUE THREAD

**Issue by yaguediop** [lula/ngx-soap#34]
Thanks M Lula however i get this error 'Access-Control-Allow-Origin' when i am in localhost:4200.
I use angular 6.
this is my code:
let headers = new HttpHeaders();
headers.append('Access-Control-Allow-Origin', 'http://localhost:4200');
    headers.append('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE');
    headers.append('Access-Control-Allow-Headers', 'Accept, X-Requested-With');
    headers.append('Access-Control-Allow-Credentials', 'true');
    this.soap.createClient('http://my_server?wsdl', {headers: headers})
      .then(client => {
        this.client = client;
        console.log('Go Client', client);
      })
      .catch(err => console.log('Error Client', err));

**Comment by lula** [comment]
@yaguediop hello! That's a cors issue. Either you use a proxy to test or you make your server accept your origin (Access-Control-Allow-Origin header set on server)
