### ISSUE TITLE
CORS problem

### ISSUE THREAD

**Issue by AnaflaviaDiaz** [lula/ngx-soap#37]
![image](https://user-images.githubusercontent.com/15807118/50983671-ef784a80-14cd-11e9-86a3-57363ec264cb.png)
How can I fix this problem with CORS?
![image](https://user-images.githubusercontent.com/15807118/50983856-66adde80-14ce-11e9-96af-678707729033.png)
![image](https://user-images.githubusercontent.com/15807118/50983791-454cf280-14ce-11e9-94fb-cd46ea50cbab.png)

**Comment by RezaRahmati** [comment]
@lula angular proxy only works when you do `ng serve`, if you build by `ng build` you can't set proxy, and CORS issue happens

**Comment by lula** [comment]
Yes, that's normal. CORS issues have nothing to do with this lib. You have to have your client whitelisted in the server, or use some reverse proxy.

**Comment by RezaRahmati** [comment]
@lula thanks for fast response, the server white listed the client and urls and methods, the issue is I don't see any preflight request (OPTION) being send, which usually should be.

**Comment by lula** [comment]
@RezaRahmati you're welcome :). I don't think the preflight request is automatically done by the browser, I believe you should do it yourself as you need to add headers to the (second) request.

**Comment by RezaRahmati** [comment]
@lula OK, anyway preflight request are sent by browser
see https://developer.mozilla.org/en-US/docs/Glossary/Preflight_request paragraph 3
