### ISSUE TITLE
Upload Attachment MTOM,I want achieve along with document and xml. 

### ISSUE THREAD

**Issue by swaminathanmca** [lula/ngx-soap#49]
import { NgxSoapService, Client, ISoapMethodResponse } from 'ngx-soap';
import { from } from 'rxjs'
constructor(private soap: NgxSoapService) {
    const promise =  this.soap.createClient('serviceimplPort')
    from(promise).subscribe(client => this.client = client);
  }
fileChange(event) {
    const fileList: FileList = event.target.files;
    this.fileName = fileList[0].name;
     this.selectedFile =  event.target.files[0];
    }
onSubmit(document) {
    const token = wsse({ username: this.userName, password: this.password });

    const body = {
      file: this.selectedFile
    };
   '<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:wsdl="http://service.wsvc.mhb.crimsonlogic.com/wsdl">' +
      '<soapenv:Header><wsse:Security soapenv:mustUnderstand="1" xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"><wsse:UsernameToken wsu:Id="UsernameToken-4C616D2C88CB4E2F9915586128832798"><wsse:Username>'+this.userName+'</wsse:Username>' +
      '<wsse:Password Type="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordDigest">' + token.getPasswordDigest()  + '</wsse:Password><wsse:Nonce EncodingType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-soap-message-security-1.0#Base64Binary">' + token.getNonceBase64() + '</wsse:Nonce><wsu:Created>' + token.getCreated() + '</wsu:Created></wsse:UsernameToken></wsse:Security>' +
      '</soapenv:Header>' +
      '<soapenv:Body>' +
      '<wsdl:SubmitMessageRequest>'+
      '<wsdl:DocumentType>'+ document + '</wsdl:DocumentType>'+
      ' <wsdl:Subject>'+ this.fileName+ '</wsdl:Subject>'+
      ' <wsdl:PayloadName>'+
      '  <wsdl:href>cid:'+ this.fileName+ '</wsdl:href>'+
      '  </wsdl:PayloadName>'+
      '  <wsdl:AttachmentFile>'+
      '  <wsdl:href>?</wsdl:href>'+
      '   </wsdl:AttachmentFile>'+
      '   </wsdl:SubmitMessageRequest>'+
      '  </wsdl:MessageSubmission>'+
      '</soapenv:Body>' +
      '</soapenv:Envelope>';
 (<any>this.client).Add(body).subscribe((res: ISoapMethodResponse) =>    console.log(res.result.AddResult));
 }

![err](https://user-images.githubusercontent.com/25892773/58552366-da5b4880-822f-11e9-8867-8571785014e5.png)

**Comment by lula** [comment]
MTOM support has been added, with #70 , thanks to [@kverhoef](https://github.com/kverhoef).
