### ISSUE TITLE
Magento SOAP API

### ISSUE THREAD

**Issue by OliverTr54** [lula/ngx-soap#7]
Hey @lula ,

how can I use your code to access a Magento API (1.9.x). I successfully initialized a client by the WSDL, but I'm not able to login or to invoke any other function. Couly it be, that Magento is using XMLRPC?

Do you have some sample code for this issue?

Thanks a lot,
Oliver

**Comment by lula** [comment]
Hello @OliverTr54 I never used Magento, I'm not sure I can help. From what I can see in the doc, it's SOAP or XML-RPC, but I don't know if you can use both or not (perhaps the two protocol are exclusives, or they must be activated somehow, ...). Anyway, quickly checking the doc, it seem like you have to call some operations. Here is  the doc I was checking:

[http://devdocs.magento.com/guides/m1x/api/soap/introduction.html#Introduction-SOAPAPIVersionv2](http://devdocs.magento.com/guides/m1x/api/soap/introduction.html#Introduction-SOAPAPIVersionv2)
