### ISSUE TITLE
WS- Security

### ISSUE THREAD

**Issue by hherraz** [lula/ngx-soap#8]
I want to be able to access an api with security ssl tls, but I can not invoke the following:

new soap.WSSecurityCert(privateKey, publicKey, password);
  client.setSecurity(wsSecurity);

like node-soap

**Comment by lula** [comment]
Hello @hherraz this feature is not ported yet from node-soap. In the future (hopefully near) I'll try to port it in this library.

**Comment by lula** [comment]
hello @hherraz if you ever want to try this again, you might download the latest version from npm. Cheers!

**Comment by hherraz** [comment]
THX Works Fine!!!

**Comment by lula** [comment]
Thanks for your confirmation @hherraz ! Issue closed.

**Comment by chrisengelsma** [comment]
Hi @lula, I must not be seeing something, but could you advise on how to call this and apply it? I can't instantiate it since it's an interface.
