### ISSUE TITLE
Angularjs 9 ngx soap not working...

### ISSUE THREAD

**Issue by Henry667** [lula/ngx-soap#81]
Hello ngx-soap, is there any way to add your lib in my latest angular project. When ever i tried i got error.

error while compiling
WARNING in Entry point 'ngx-soap' contains deep imports into '/home/sunnynegi/projects/my-app/node_modules/crypto-js/sha1', '/home/sunnynegi/projects/my-app/node_modules/crypto-js/enc-base64'. This is probably not a problem, but may cause the compilation of entry points to be out of order.

ERROR in The target entry-point "ngx-soap" has missing dependencies:

uuid/v4

package.json

`{
  "name": "my-app",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~9.1.9",
    "@angular/common": "~9.1.9",
    "@angular/compiler": "~9.1.9",
    "@angular/core": "~9.1.9",
    "@angular/forms": "~9.1.9",
    "@angular/platform-browser": "~9.1.9",
    "@angular/platform-browser-dynamic": "~9.1.9",
    "@angular/router": "~9.1.9",
    "buffer": "^5.6.0",
    "concat-stream": "^2.0.0",
    "core-js": "^3.6.5",
    "crypto-js": "^4.0.0",
    "events": "^3.1.0",
    "lodash": "^4.17.15",
    "ngx-soap": "^0.6.3",
    "rxjs": "~6.5.4",
    "sax": "^1.2.4",
    "stream": "0.0.2",
    "tslib": "^1.10.0",
    "uuid": "^8.1.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.901.7",
    "@angular/cli": "~9.1.7",
    "@angular/compiler-cli": "~9.1.9",
    "@types/node": "^12.11.1",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^5.1.2",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~5.0.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~2.1.0",
    "karma-jasmine": "~3.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~3.8.3"
  }
}
`
Any help would be appreciated

**Comment by amitsodmise** [comment]
Downgrade uuid version  
npm i uuid@3.3.2 try this

**Comment by lj67** [comment]
Would love to know if the fix suggested by amitsodmise worked?

**Comment by AndreyBespamyatnov** [comment]
> Would love to know if the fix suggested by amitsodmise worked?

I made a PR with updated version of Angular: https://github.com/lula/ngx-soap/pull/87
